### ISSUE TITLE
App crashes when end call.

### ISSUE THREAD

**Issue by gstream** [runamedia/rtcsip#13]
Android demo get crash when end call.

**Comment by morosev** [comment]
@gstream: I haven't noticed that. Even, I used to make many successive calls on Android.
Can you reproduce the problem every time, or it happens occasionally?
I will check the Android again.

**Comment by gstream** [comment]
I get this error every time with outbound proxy set.

**Comment by morosev** [comment]
@gstream:  If outbound proxy is not used the crash cannot be reproduced. I have to set up the environment to fix this error. So, going to run my own proxy for testing purposes. Do you have any advice about setting the outbound proxy? I use FreeSWITCH as a SIP server.

**Comment by gstream** [comment]
You can use my user info, outbound proxy, sip server.

I can share you if you are ok.

What do you think?

**Comment by morosev** [comment]
Sure, I would appreciate this. That will save some time.
If the user info is confident, you can send all parameters to my email: morosev@runamedia.com.
Thx

**Comment by gstream** [comment]
I sent sip account options via email.
I want to make sure that I can use your library to make client for my own sip server.

**Comment by gstream** [comment]
Did you test your library with my sip server?

**Comment by gstream** [comment]
Hi morosev
Any update for this issue ?

**Comment by morosev** [comment]
Hi @gstream.

I tried to make a call between two devices using your server. I can register, but cannot establish a call. Are you able to make a video call between devices?

**Comment by gstream** [comment]
Thanks morosev
I will check again and let you know if you are ok.

**Comment by gstream** [comment]
Hi morosev
I've tested with jssip.net with credentials I sent you.
It works without problems
Try from chrome https://tryit.jssip.net/

**Comment by gstream** [comment]
![275d5126d688433d1a1599aff44abdb2f64f7cef7032a31de0 pimgpsh_thumbnail_win_distr](https://cloud.githubusercontent.com/assets/17048847/14535007/603dd18c-0274-11e6-8e38-92eaa92d28c5.jpg)

**Comment by gstream** [comment]
![ef01e8db0d6c2bac0cf1f3bd5aa690016029bf1726ae3b70ac pimgpsh_thumbnail_win_distr](https://cloud.githubusercontent.com/assets/17048847/14535015/69b12aca-0274-11e6-900b-d88b20fae494.jpg)

**Comment by gstream** [comment]
Hello morosev
Did you check this issue again?

**Comment by morosev** [comment]
@gstream

I succeeded to initialize a call using your server between two devices (iOS and Android). I can see from the log that device receives INVITE message, but looks like SDP content is wrong. It is changed by your SIP server because the SDP is not the one sent from caller side.

There is a SIP message:

INVITE sip:user_9xhnzmxpna@109.245.35.119:50975;transport=tcp SIP/2.0
Via: SIP/2.0/TCP 174.36.47.4;branch=z9hG4bK63d1.6af3536689b89ad6596628f8b5821a2d.0;i=7ef
Via: SIP/2.0/TCP 174.36.47.3:11000;branch=z9hG4bKj3QaZD714jU8c
Max-Forwards: 48
Record-Route: sip:174.36.47.4;transport=tcp;lr=on;ftag=gt3aQec0eFQZN
Contact: sip:mod_sofia@174.36.47.3:11000;transport=tcp
To: sip:user_9xhnzmxpna@109.245.35.119:50975;transport=tcp
From: "Admin2 Android" sip:1000@testappandroid.vozy.co;tag=gt3aQec0eFQZN
Call-ID: d71f41d4-02f4-11e6-ba53-9fa875777489
CSeq: 90022000 INVITE
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, PRACK, NOTIFY, PUBLISH, SUBSCRIBE
Content-Disposition: session
Content-Type: application/sdp
Supported: precondition, 100rel, path, replaces
User-Agent: 2600hz
Allow-Events: talk, hold, conference, presence, as-feature-event, dialog, line-seize, call-info, sla, include-session-description, presence.winfo, message-summary, refer
Remote-Party-ID: "Admin2 Android" sip:1000@testappandroid.vozy.co;party=calling;screen=yes;privacy=off
Content-Length: 422
v=0
o=FreeSWITCH 1460691844 1460691845 IN IP4 174.36.47.3
s=FreeSWITCH
c=IN IP4 174.36.47.3
t=0 0
m=audio 24284 RTP/AVP 111 0 8 101 13
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10; useinbandfec=1
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=ptime:20
m=video 19914 RTP/AVP 102 34 31
a=rtpmap:102 H264/90000
a=rtpmap:34 H263/90000
a=rtpmap:31 H261/90000

Also, I have't noticed crash while executing this scenario.

I will send to you GIT patch file over email with changes that were applied to the code.

**Comment by gstream** [comment]
Hello morosev
Thanks for your detailed report.

I m new to here so I m not familiar with this field.

Do you think my sip configuration has something wrong?

Thanks

**Comment by morosev** [comment]
@gstream 

Yes, server doesn't send right message. You have to take a look into server log and to see and compare incoming and outgoing messages. In WebRTC case the SDP content of received INVITE message should be identical to the message that was sent from the caller device.

Check https://github.com/runamedia/rtcsip/blob/master/README.md for FreeSWITCH configuration.

**Comment by gstream** [comment]
Thanks morosev. I will check again my server configuration.

**Comment by gstream** [comment]
Hello morosev
My current freeswitch and registered users can make call with VoIP softphones such as zoiper and xlite.

I m not sure what is wrong now. :(

What about only audio call?
Do you think I can't make audio call with your demo ?

Also the app crashes when re-connect after disconnect.

**Comment by gstream** [comment]
hello morosev
I can make call between two devices.
But I can't hear anything. 
Also I get crash when end call.
what should i do? thanks

**Comment by morosev** [comment]
Hi @gstream.
You can make calls using Zopier and Xlite, because those calls are not peer to peer, but media is relayed over FreeSwitch. WebRTC is peer to peer only and there must be used ICE protocol to traverse NAT. If you don't send ICE candidates to other party, there is no way to establish a call in WebRTC. SDP, for exaple, must contain ICE data. That's why signalling server in WebRTC scenario is not allowed to modify SDP data.
Check the server log and track the content of INVITE message. "inbound-bypass-media" FreeSwitch parameter must be set to "true" to bypass media packets on server.
Thank's for reporting new crashes. I will file them and fix.

**Comment by gstream** [comment]
Hello morosev

If I set "inbound-bypass-media" as "true", can I record call on server ?

**Comment by morosev** [comment]
No, WebRTC doesn't talk over the server - there is only direct communication between peers.
Maybe there is some way to make a media traffic through the server, but it wouldn't be a natural solution for WebRTC.
